insert into person (first_name, last_name, enabled, gender, address) values 
('Stacee', 'Chelley', b'0', 'Male', '9452 Clarendon Center'),
('Ronalda', 'Cockin', b'1', 'Female', '86204 Novick Road'),
('Doe', 'Southwood', b'0', 'Female', '92 Crest Line Road'),
('Jamill', 'Twelvetrees', b'0', 'Male', '82612 Debs Point'),
('Pate', 'Mackiewicz', b'1', 'Male', '8 Redwing Pass'),
('Erna', 'McMarquis', b'1', 'Female', '770 Commercial Pass'),
('Martelle', 'Rableau', b'1', 'Female', '5 Melby Point'),
('Anne-marie', 'Nason', b'0', 'Female', '04466 Arizona Lane'),
('Jeremie', 'Palfreman', b'1', 'Male', '9308 Sommers Avenue'),
('Allix', 'Yonnie', b'1', 'Female', '84185 Porter Alley'),
('Edik', 'Dingle', b'0', 'Male', '0 Marcy Park'),
('Pascale', 'Harce', b'0', 'Male', '49653 Eagan Pass'),
('Emmie', 'Climpson', b'0', 'Female', '98111 Vahlen Avenue'),
('Alastair', 'Livezley', b'1', 'Male', '07 Forest Dale Terrace'),
('Randee', 'Alliot', b'1', 'Female', '35147 Roth Hill'),
('Galvan', 'Harsum', b'1', 'Male', '820 Knutson Park'),
('Schuyler', 'Conklin', b'0', 'Male', '56 Kennedy Center'),
('Mirabella', 'Sabberton', b'0', 'Female', '036 Meadow Valley Court'),
('Alicia', 'Yesinin', b'0', 'Female', '3 Mosinee Trail'),
('Yurik', 'Frays', b'1', 'Male', '16 Glendale Circle'),
('Egan', 'Novak', b'0', 'Male', '77867 Loomis Junction'),
('Antons', 'Tieraney', b'0', 'Male', '0130 Vera Terrace'),
('Fionna', 'Doidge', b'0', 'Female', '1 West Terrace'),
('Marcelia', 'Ivy', b'1', 'Female', '414 Vidon Way'),
('Callean', 'Banbury', b'0', 'Male', '28543 Weeping Birch Road'),
('Al', 'Forseith', b'1', 'Male', '79 Susan Hill'),
('Jackson', 'Thirkettle', b'0', 'Male', '95356 Artisan Parkway'),
('Hilton', 'Lucus', b'1', 'Male', '46559 Summer Ridge Crossing'),
('Britt', 'Koenen', b'1', 'Male', '856 Redwing Alley'),
('Robin', 'Swetman', b'1', 'Male', '68 Mcguire Park'),
('Barbette', 'Brandino', b'0', 'Female', '84 Ohio Point'),
('Dennis', 'Duncombe', b'0', 'Male', '107 Cambridge Circle'),
('Kesley', 'Roskruge', b'1', 'Female', '3 Mccormick Center'),
('Wilhelmine', 'Bunkle', b'1', 'Female', '2554 Butterfield Center'),
('Skip', 'Breche', b'1', 'Male', '456 Stuart Trail'),
('Darla', 'Paxforde', b'1', 'Female', '88 Bobwhite Alley'),
('Antonin', 'Haburne', b'1', 'Male', '520 Larry Junction'),
('Shae', 'Moulding', b'1', 'Male', '63 Bonner Way'),
('Alma', 'Bonnet', b'0', 'Female', '047 Walton Alley'),
('Hettie', 'Crathorne', b'0', 'Female', '09 Hanover Center'),
('Egon', 'Woodland', b'0', 'Male', '12777 Village Court'),
('Ferrel', 'Bearcock', b'1', 'Male', '173 Kropf Pass'),
('Urban', 'Kimmings', b'1', 'Male', '9 Crescent Oaks Trail'),
('Carmelia', 'Wheatley', b'1', 'Female', '72638 8th Park'),
('Alexa', 'Comer', b'1', 'Female', '9 Waubesa Crossing'),
('Mathias', 'Pairpoint', b'0', 'Male', '2677 Mifflin Crossing'),
('Ludovico', 'Maevela', b'0', 'Male', '6175 Pennsylvania Center'),
('Jarib', 'Sangar', b'1', 'Male', '1551 Maryland Drive'),
('Matty', 'Grooby', b'1', 'Male', '0731 Eastlawn Crossing'),
('Rriocard', 'Gascone', b'1', 'Male', '2910 Shoshone Street'),
('Miguelita', 'Scollard', b'1', 'Female', '175 Macpherson Point'),
('Zabrina', 'Gherardi', b'1', 'Female', '493 Mayer Alley'),
('Immanuel', 'Lawrey', b'1', 'Male', '781 Cambridge Lane'),
('Ximenes', 'Knivett', b'0', 'Male', '8459 Bonner Terrace'),
('Zacharia', 'Scotchforth', b'1', 'Male', '5783 Eliot Junction'),
('Stanley', 'Caskey', b'1', 'Male', '5342 Coleman Plaza'),
('Fina', 'Stuchbery', b'1', 'Female', '1 David Plaza'),
('Merl', 'Gribbins', b'1', 'Female', '89175 Weeping Birch Crossing'),
('Mariska', 'Hicken', b'0', 'Female', '22159 Elgar Alley'),
('Caroljean', 'Ugo', b'1', 'Female', '20698 Glendale Trail'),
('Warden', 'Fanstone', b'1', 'Male', '24170 Oak Valley Park'),
('Theodore', 'Slopier', b'0', 'Male', '10256 Holmberg Crossing'),
('Magdaia', 'Huzzay', b'0', 'Female', '0 Ludington Junction'),
('Jarrad', 'Tredger', b'0', 'Male', '271 Barby Place'),
('Kiele', 'Jamson', b'1', 'Female', '5029 Superior Terrace'),
('Zulema', 'Betancourt', b'0', 'Female', '6369 Dunning Pass'),
('Nikolos', 'Ville', b'0', 'Male', '71543 Brentwood Park'),
('Ragnar', 'Basill', b'1', 'Male', '80 Southridge Center'),
('Wilbur', 'Robuchon', b'0', 'Male', '582 Sage Way'),
('Vickie', 'Moyle', b'1', 'Female', '7 Saint Paul Court'),
('Jammal', 'Wemm', b'0', 'Male', '5020 Valley Edge Park'),
('Gamaliel', 'Dorrance', b'1', 'Male', '94253 Valley Edge Trail'),
('Sara', 'Wycherley', b'0', 'Female', '298 Sugar Road'),
('Aile', 'Occleshaw', b'1', 'Female', '1314 Waywood Point'),
('Madonna', 'Petruk', b'0', 'Female', '907 Lerdahl Point'),
('Ethelda', 'Selwyn', b'0', 'Female', '7676 Service Crossing'),
('Gualterio', 'Gidden', b'1', 'Male', '76437 Merrick Pass'),
('Tanya', 'Eden', b'1', 'Female', '4 Lakeland Point'),
('Chrysa', 'Oxterby', b'0', 'Female', '45 Merchant Center'),
('Tammara', 'Sivil', b'1', 'Female', '4 Muir Junction'),
('Gabbi', 'Stoate', b'0', 'Female', '84 Farwell Circle'),
('Hussein', 'Gandar', b'1', 'Male', '65 Northland Trail'),
('Donella', 'Brittlebank', b'0', 'Female', '13 Shelley Terrace'),
('Clayton', 'O''Ruane', b'0', 'Male', '170 Brown Alley'),
('Joyan', 'Aldrick', b'0', 'Female', '2084 Loeprich Avenue'),
('Blakelee', 'Fardon', b'1', 'Female', '90 Hollow Ridge Terrace'),
('Carson', 'Brompton', b'0', 'Male', '43295 4th Drive'),
('Ginevra', 'Chantrell', b'1', 'Female', '504 Chinook Circle'),
('Bryn', 'Di Claudio', b'1', 'Male', '037 Swallow Circle'),
('Kristal', 'Filippucci', b'0', 'Female', '1 Pankratz Street'),
('Clevey', 'Faulo', b'0', 'Male', '6219 Golf View Trail'),
('Noam', 'Houlson', b'1', 'Male', '01 Mockingbird Street'),
('Herve', 'Casale', b'1', 'Male', '487 East Circle'),
('Rab', 'Teresia', b'1', 'Male', '12 Gale Lane'),
('Penelope', 'Pike', b'0', 'Female', '3 Kenwood Way'),
('Elana', 'Linnock', b'0', 'Female', '796 Ronald Regan Street'),
('Christel', 'Casper', b'0', 'Female', '73 Summit Avenue'),
('Fremont', 'Caven', b'0', 'Male', '651 Alpine Drive'),
('Cesar', 'Overpool', b'0', 'Male', '3 Milwaukee Way'),
('Juanita', 'Bony', b'0', 'Female', '9 Maple Wood Lane'),
('Rochelle', 'Gruczka', b'0', 'Female', '329 Eliot Place'),
('Eimile', 'Collidge', b'1', 'Female', '2373 Main Circle'),
('Shelden', 'Dowglass', b'1', 'Male', '257 Raven Junction'),
('Sumner', 'Vail', b'0', 'Male', '817 Randy Alley'),
('Pavel', 'Masdin', b'1', 'Male', '8 Browning Crossing'),
('Avigdor', 'Bartolomeazzi', b'0', 'Male', '0541 Bunker Hill Point'),
('Camilla', 'Erbain', b'1', 'Female', '91 Paget Alley'),
('Carissa', 'Fateley', b'0', 'Female', '9 Comanche Drive'),
('Adamo', 'Bysshe', b'1', 'Male', '24970 Corry Drive'),
('Clareta', 'Axcell', b'0', 'Female', '340 Hoffman Point'),
('Samara', 'Diaper', b'1', 'Female', '80253 Red Cloud Hill'),
('Bevan', 'Defries', b'0', 'Male', '32000 Sheridan Hill'),
('Ofella', 'Rosenzwig', b'0', 'Female', '6 Gateway Circle'),
('Maisie', 'Paradyce', b'1', 'Female', '5734 Mockingbird Avenue'),
('Humphrey', 'Fetters', b'1', 'Male', '36 5th Trail'),
('Ephraim', 'De Castri', b'1', 'Male', '059 Mallory Lane'),
('Bianka', 'Growcott', b'0', 'Female', '7027 Oakridge Parkway'),
('Esteban', 'Stainburn', b'1', 'Male', '36 Jackson Parkway'),
('Julienne', 'Geaveny', b'1', 'Female', '55351 Thierer Drive'),
('Bastian', 'Minger', b'1', 'Male', '088 Melvin Plaza'),
('Sharai', 'Drew', b'1', 'Female', '0161 Artisan Circle'),
('Bret', 'Curry', b'0', 'Male', '5 Melby Road'),
('Editha', 'Ciabatteri', b'1', 'Female', '075 Bellgrove Hill'),
('Gram', 'Jeremaes', b'1', 'Male', '557 Mcbride Drive'),
('Kleon', 'Allcorn', b'0', 'Male', '60 Dahle Junction'),
('Addy', 'Erington', b'0', 'Male', '1263 Namekagon Junction'),
('Almeda', 'McKea', b'1', 'Female', '9 Vahlen Plaza'),
('Sol', 'Myatt', b'0', 'Male', '494 Mendota Avenue'),
('Moore', 'Probet', b'0', 'Male', '89720 Hoffman Center'),
('Nickie', 'Sharratt', b'1', 'Female', '501 Mccormick Lane'),
('Roley', 'Bradnick', b'1', 'Male', '9 Golf Court'),
('Mar', 'Skep', b'0', 'Male', '813 Mockingbird Avenue'),
('Elia', 'Blanchette', b'1', 'Male', '5691 Mitchell Street'),
('Brantley', 'Arnaudi', b'1', 'Male', '81689 Arizona Place'),
('Meggie', 'Somerfield', b'1', 'Female', '406 New Castle Court'),
('Matilda', 'Capstake', b'0', 'Female', '81 Mandrake Alley'),
('Fletch', 'Antoniat', b'0', 'Male', '6 Northridge Pass'),
('Aliza', 'Kelleher', b'1', 'Female', '5181 Killdeer Park'),
('Jaquith', 'Paffitt', b'0', 'Female', '4827 Del Mar Lane'),
('Maggy', 'Speek', b'1', 'Female', '78 Granby Place'),
('Rodger', 'Albone', b'1', 'Male', '9 Hansons Way'),
('Court', 'Digwood', b'1', 'Male', '014 Grasskamp Place'),
('Nikaniki', 'Pimblotte', b'0', 'Female', '6 Darwin Park'),
('Ann', 'Bozward', b'1', 'Female', '66201 Miller Crossing'),
('Lark', 'Wanne', b'1', 'Female', '7 Amoth Court'),
('Cthrine', 'Regitz', b'1', 'Female', '68037 Arrowood Park'),
('Hildy', 'Ocklin', b'1', 'Female', '2096 Westerfield Plaza'),
('Elmore', 'Busch', b'1', 'Male', '6 Graedel Parkway'),
('Sherye', 'Ranstead', b'1', 'Female', '9 Browning Hill'),
('Mickie', 'Hegges', b'1', 'Female', '0 Sycamore Junction'),
('Vera', 'Kadwallider', b'0', 'Female', '55 Clarendon Street'),
('Hersh', 'Durrett', b'0', 'Male', '9 Declaration Lane'),
('Tyson', 'Wilby', b'0', 'Male', '1 Susan Road'),
('Roddie', 'Hamfleet', b'1', 'Male', '73 Karstens Circle'),
('Rosemaria', 'Shand', b'1', 'Female', '6 Esker Hill'),
('Phillipp', 'Iredale', b'1', 'Male', '690 Service Center'),
('Ethelred', 'Worvell', b'0', 'Male', '62739 Kenwood Avenue'),
('Chandler', 'Newns', b'1', 'Male', '34393 Texas Trail'),
('Bil', 'Mucklo', b'1', 'Male', '96 Gina Drive'),
('Griffie', 'Seldon', b'1', 'Male', '754 Hagan Trail'),
('Britte', 'Pegden', b'0', 'Female', '5464 Spaight Street'),
('Erinna', 'Baradel', b'1', 'Female', '29 Goodland Lane'),
('North', 'Eteen', b'1', 'Male', '313 Nobel Road'),
('Seline', 'Ferfulle', b'1', 'Female', '40 Fulton Circle'),
('Lethia', 'Oxley', b'1', 'Female', '7 Vermont Hill'),
('Esmaria', 'Gaukrodge', b'0', 'Female', '73436 Fuller Drive'),
('Carrissa', 'Whissell', b'0', 'Female', '27902 Rutledge Way'),
('Bonnee', 'Mewrcik', b'0', 'Female', '51 Graedel Trail'),
('Wenonah', 'Sawl', b'1', 'Female', '196 Pleasure Street'),
('Reube', 'Abbati', b'1', 'Male', '328 Shasta Center'),
('Ferguson', 'Monday', b'1', 'Male', '62736 Anhalt Crossing'),
('Abbott', 'Duckers', b'1', 'Male', '615 Northland Way'),
('Bessie', 'Bartosch', b'1', 'Female', '996 Utah Trail'),
('Henka', 'Snoxill', b'0', 'Female', '438 Stephen Road'),
('Brewer', 'Blais', b'1', 'Male', '70 Pierstorff Parkway'),
('Cleo', 'Standon', b'0', 'Female', '51 Maple Circle'),
('Karlie', 'Doodson', b'1', 'Female', '66717 Comanche Circle'),
('Gwenette', 'Henrych', b'0', 'Female', '57 Barnett Street'),
('Christophorus', 'McClaughlin', b'0', 'Male', '7 John Wall Road'),
('Dina', 'Ankrett', b'1', 'Female', '9 Veith Court'),
('Cecilius', 'Phettis', b'1', 'Male', '34 Algoma Alley'),
('Kacy', 'Brailsford', b'1', 'Female', '629 Crest Line Center'),
('Lyndsie', 'Whitechurch', b'1', 'Female', '79 Clove Center'),
('Inger', 'Pickless', b'1', 'Female', '1545 Lunder Road'),
('Willem', 'Farnill', b'1', 'Male', '7774 Thackeray Trail'),
('Reina', 'Agge', b'1', 'Female', '9 Buhler Lane'),
('Calv', 'Rodolf', b'1', 'Male', '7 Towne Point'),
('Zenia', 'Skynner', b'0', 'Female', '8 Forster Court'),
('Candra', 'MacMakin', b'0', 'Female', '65 Nobel Place'),
('Gennie', 'Pohling', b'0', 'Female', '477 Moland Way'),
('Skip', 'Korpolak', b'0', 'Male', '9 Loomis Place'),
('Keven', 'Pietruszewicz', b'1', 'Male', '2 Lindbergh Crossing'),
('Zak', 'Margetts', b'0', 'Male', '87054 New Castle Parkway'),
('Adrien', 'Klewer', b'0', 'Male', '691 La Follette Center'),
('Aylmar', 'Quinet', b'0', 'Male', '853 Kim Street'),
('Thibaud', 'Tinmouth', b'1', 'Male', '811 Shoshone Court'),
('Kaine', 'Ratcliff', b'0', 'Male', '1757 Anhalt Alley'),
('Sarita', 'Medina', b'0', 'Female', '9498 Cherokee Lane'),
('Currey', 'Pople', b'0', 'Male', '679 Fallview Alley'),
('Janenna', 'Flucker', b'0', 'Female', '287 Fisk Plaza');
